### ISSUE TITLE
API Connection to World Bank (and ultimately other banks)

### ISSUE THREAD

**Issue by silson** [USStateDept/bids#170]
Convince World Bank of the business case for improving (slightly) their data stream so that we can collect it via API and automatically include new projects.

**Comment by brodydittemore** [comment]
World Bank: http://web.worldbank.org/projects/templates/JspToExcel.jsp?category=simsearch&query=ALL&sortorder=DESC&sortby=BOARDSORTDATE&status=ALL
IADB: http://www.iadb.org/en/project-procurement/procurement-notices-xls,8323.html?isajaxrequest&keyword=&ProjectNumber=&dateFrom=&dateTo=&order=desc&sort=date

All other banks do not appear to have a public API. Recommend reaching out to them to confirm. Otherwise, we could scrape.

**Comment by SchwartzTP** [comment]
Let's see what happens in this meeting with COmmerce today -- maybe that will give us some answers.

Also please be sure to take a look at http://developer.trade.gov/trade-leads.html -- they report having canadian and uk leads as well as our BIDS data.  Can we start to integrate that from their API
