### ISSUE TITLE
Georgia vs. Georgia

### ISSUE THREAD

**Issue by SchwartzTP** [USStateDept/bids#258]
Three entries for the Republic of Georgia are being mapped as being in the U.S. state of Georgia.  How do we make sure BIDS distinguishes between the two?

**Comment by SchwartzTP** [comment]
I went back into the system and manually edited the three entries. It appears someone had typed in 'Georgian' instead of using the dropdown box.  It appears as if manual entry is now not available in the country field, so I believe this is resolved.  I'd like one of our professional team to review this comment before closing it.

**Comment by brodydittemore** [comment]
I ran through a number of tests and this bug was fixed by @leroybryant with #250.

If a user selects "Georgia" from the country dropdown, then enters either "Georgia", "Georgian", or "Atlanta" as the specific location, BIDS correctly geocodes to Georgia the country.

However, if a user selects "Georgia" from the dropdown, and for specific location enters "Atlanta, Georgia" then BIDS will geocode the lead to Atlanta, Georgia, USA. This would be highly unlikely for someone to enter into BIDS, that I think we can call this resolved.
